# Book settings
title: Applied Machine Learning in Python
author: Andreas C. Müller
logo: logo.png
navbar_number_sections: true
exclude_patterns: ['notebooks-old', 'data', 'README.md']

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex
  