# Book settings
title: Applied Machine Learning in Python
author: Andreas C. Müller
logo: logo.png
exclude_patterns: ['notebooks-old', 'data', 'README.md', 'slides_to_book.ipynb', 'slides_markdown']

execute:
  execute_notebooks: 'off'

html:
  navbar_number_sections: true


latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions: ['sphinx.ext.todo']
  todo_include_todos: True